name: My frist workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo    
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "My frirst github actions job"

        - name: list files
          run: 'ls -lrth'

        - name: Read file
          run: cat README.md