name: My frist workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo    
          uses: actions/checkout@v4

        - name: List and read files
          run: | 
            echo "My frirst github actions job"
            ls -larth
            cat README.md
        
        - name: Generate ASCII Art work
          run: cowsay -f dragon "Run take cover, I am a DRAGON .... FIRE!" >> dragon.txt


      #  - name: list files
       #   run: 'ls -lrth'

       # - name: Read file
      #    run: cat README.md