name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsat program
          run: sudo apt-get insatll cowsay -y

        - name: Executing Cowsay program
          run: cowsay -f dragon "Run take cover, I am a DRAGON .... FIRE!" >> dragon.txt
        
        - name: Sleep for 30 seccond
          run: sleep 30

    test_job_2:
        runs-on: macos-latest
        steps:
        - name: Sleep for 10 secconds
          run: sleep 10

        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo deploying ... ... ..
       