name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo    
          uses: actions/checkout@v4

        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run take cover, I am a DRAGON .... FIRE!" >> dragon.txt

        - name: Test file exists
          run: grep -i "dragon" dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: List repo files
          run: 'ls -lrtha'